- hosts: orclients
  become: true
  become_method: sudo
  become_user: oracle
  vars:
    allow_world_readable_tmpfiles: True


  tasks:
    - name: run db start up
      shell:
        cmd: |
          lsnrctl start
          sqlplus / as sysdba @startup.sql
      environment:
        ORACLE_HOME: "/u01/app/product/19c"
        ORACLE_SID: "db19000"
        PATH: "$PATH:/u01/app/product/19c/bin"

    - name: copy shell script to oracle servers
      copy:
        src: /home/cecuser/demo-files/demo_shell.sh
        dest: /home/oracle/demo_shell.sh

    - name: make demo_shell script executable
      file: dest=/home/oracle/demo_shell.sh mode=+x

    - name: run shell script in oracle servers
      shell: "/home/oracle/demo_shell.sh"

    - name: fetch log
      fetch:
        src: "/home/oracle/discover_1.txt"
        dest: "/tmp/fetched/{{inventory_hostname}}-discover_1.txt"
        flat: true
