- hosts: orclients
  become: true
  become_method: sudo
  become_user: oracle
  vars:
    allow_world_readable_tmpfiles: True


  tasks:
    - name: copy shell script to oracle servers
      copy:
        src: /home/cecuser/demo-files/demo_shell.sh
        dest: /home/oracle/demo_shell.sh

    - name: make demo_shell script executable
      file: dest=/home/oracle/demo_shell.sh mode=+x

    - name: run shell script in oracle servers
      shell: "export PATH=$PATH:/u01/app/product/19c/bin; /home/oracle/demo_shell.sh"
      environment:
          ORACLE_BASE: "/u01/app/oracle"
          ORACLE_SID: "db19000"
          ORACLE_HOME: "/u01/app/product/19c"
          SQLPLUS_HOME: "/u01/app/oracle/product/19c/bin/sqlplus"
          PATH: "/usr/bin:/etc:/usr/sbin:/usr/ucb:$HOME/bin:/usr/bin/X11:/sbin:.:$ORACLE_HOME/bin:$ORACLE_HOME/OPatch"


    - name: fetch log
      fetch:
        src: "/home/oracle/discover_1.txt"
        dest: "/tmp/fetched/{{inventory_hostname}}-discover_1.txt"
        flat: true
