- hosts: all
  vars:
    allow_world_readable_tmpfiles: True
    
  tasks:
    - name: whoami?
      command: whoami
      register: command_output

    - debug:
        var: command_output.stdout_lines
