- hosts: orclients
  become: true
  become_method: sudo
  become_user: oracle
  vars:
    allow_world_readable_tmpfiles: True

  tasks:
    - name: does the logfile exist
      stat:
        path: /home/oracle/discover_1.txt
      register: sym

    - debug:
        msg: "discover_1.txt does NOT exist"
      when: sym.stat.exists == False

    - debug:
        msg: "discover_1.txt does exist"
      when: sym.stat.exists == True

    - name: delete the logfile
      file:
        path: /home/oracle/discover_1.txt
        state: absent

    - name: does the logfile exist
      stat:
        path: /home/oracle/discover_1.txt
      register: sym

    - debug:
        msg: "discover_1.txt does NOT exist"
      when: sym.stat.exists == False

    - debug:
        msg: "discover_1.txt does exist"
      when: sym.stat.exists == True