---

- hosts: orclients
  become: yes
  become_method: sudo
  become_user: oracle
  vars:
    allow_world_readable_tmpfiles: True

  tasks:
    - name: whoami?
      command: whoami
      register: command_output

    - debug:
        var: command_output.stdout_lines

    - name: Print all available facts
      debug:
        var: ansible_facts

    - name: Copy ansible facts to a file.
      copy:
        content: "{{ ansible_facts }}"
        dest: /tmp/ansible_facts.json
        delegate_to: localhost
